//styles start

const CommonGridStyle = {
	margin: 10,
	display: 'flex',
	justifyContent: 'center',
	alignItems: 'center',
}
const AddressGridStyle = CommonGridStyle
//styles end

const LoginCredentials = [
	{
		type: 'text',
		id: 'Employer_Contact_Email',
		label: 'Email ID',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'password',
		id: 'Password_new',
		label: 'Password',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'password',
		id: 'Password_new_confirm',
		label: 'Confirm Password',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
]

const CompanyInformation = [
	{
		type: 'text',
		id: 'Name_of_the_company',
		label: 'Name of Company',
		errorText: 'Invalid input',
		helpContent: "Name of the Recruiter's Company",
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'date',
		placeholder: 'yyyy-mm-dd',
		id: 'Establishment_Date',
		label: 'Establishment Date',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'Type_of_Organization',
		label: 'Type of Organization',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},

	{
		type: 'text',
		id: 'Nature_of_Business',
		label: 'Nature of Business',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},

	{
		type: 'text',
		id: 'Employer_Contact',
		label: 'Office Contact Number',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'Website',
		label: 'Website',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
]

const CompanyPermanentAddress = [
	{
		type: 'text',
		id: 'Employer_Permanent_Address_Line1',
		label: 'Address Line 1',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: AddressGridStyle,
	},
	{
		type: 'text',
		id: 'Employer_Permanent_Address_Line2',
		label: 'Address Line 2',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: AddressGridStyle,
	},
	{
		type: 'text',
		id: 'PinCode_Permanent',
		label: 'Pincode',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'State_Permanent',
		label: 'State',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'Country_Permanent',
		label: 'Country',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
]

const CompanyCorrespondenceAddress = [
	{
		type: 'text',
		id: 'Employer_Correspondence_Address_Line1',
		label: 'Address Line 1',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: AddressGridStyle,
	},
	{
		type: 'text',
		id: 'Employer_Correspondence_Address_Line2',
		label: 'Address Line 2',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: AddressGridStyle,
	},
	{
		type: 'text',
		id: 'PinCode_Correspondence',
		label: 'Pincode',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'State_Correspondence',
		label: 'State',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'Country_Correspondence',
		label: 'Country',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
]

const FirstPointOfContact = [
	{
		type: 'text',
		id: 'Employer_Registration_Contacts_Contact_Person',
		label: "Person's Name",
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'text',
		id: 'Employer_Registration_Contacts_Designation',
		label: "Person's Designation",
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'number',
		id: 'Employer_Contact_Phone',
		label: 'Phone number',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
	{
		type: 'number',
		id: 'Employer_Contact_Mobile',
		label: 'Mobile number',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
]

export const formFields = {
	LoginCredentials: LoginCredentials,
	CompanyInformation: CompanyInformation,
	FirstPointOfContact: FirstPointOfContact,
	CompanyPermanentAddress: CompanyPermanentAddress,
	CompanyCorrespondenceAddress: CompanyCorrespondenceAddress,
}

/*
	{
		type: '{text/number/date/password}',
		id: '{object property name}',
		label: '{name of the field represented on client page}',
		errorText: '{error visible if data is incorrect}',
		helpContent: '{text visible on clicking (?)}',
		defaultValue: '{value in the field by default}',
		required: '{true/false}',
		style: {style object},
	},

	{
		type: 'text',
		id: 'Type_of_Organization',
		label: 'Type of Organization',
		errorText: 'Invalid input',
		helpContent: 'Help Content',
		defaultValue: '',
		required: true,
		style: CommonGridStyle,
	},
*/

/*
{
    "Name_of_the_company" : "",
    "Establishment_Date" : "" ,
    "Type_of_Organization" : "",
    "Nature_of_Business" : "",
    "Employer_Permanent_Address_Line1" : "",
    "Employer_Permanent_Address_Line2" : "",
    "Employer_Permanent_Address_Line3" : "",
    "PinCode_Permanent" : ,
    "Country_Permanent" : "",
    "State_Permanent" : "",
    "Employer_Contact" : ,
    "Website" : "",
    "Employer_Registration_Contacts_Contact_Person" : "",
    "Employer_Registration_Contacts_Designation" : "",
    "Employer_Correspondence_Address_Line1" : "",
    "Employer_Correspondence_Address_Line2" : "",
    "Employer_Correspondence_Address_Line3" : "",
    "PinCode_Correspondence" : ,
    "Country_Correspondence" : "",
    "State_Correspondence" : "",
    "Employer_Contact_Phone" : "",
    "Employer_Contact_Mobile" : "",
    "Employer_Contact_Email" : "",
    "Password_new" : "Password"
}
*/
